/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author ly.doan
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    private int GVCN = 0;
    private String userName, lop;

    public TrangChu(String role, String userName) {
        initComponents();
        icon();
        setSize(664, 411);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.userName = userName;
        showAnh();
        showButton(role);
    }

    public void icon() {

        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("school.png")));
    }

    public TrangChu(String role, String userName, int GVCN, String Lop) {
        initComponents();
        icon();
        setSize(664, 411);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.userName = userName;
        this.lop = Lop;
        showAnh();
        showButton(role);
        this.GVCN = GVCN;
    }

    public void showButton(String role) {
        if (role.equals("ST")) {
            btnQuanLi.setEnabled(false);
            btnNhapDiem.setEnabled(false);
            btnXemDiem.setEnabled(true);
        } else if (role.equals("TC")) {
            btnQuanLi.setEnabled(false);
            btnNhapDiem.setEnabled(true);
            btnXemDiem.setEnabled(false);
        } else if (role.equals("AD")) {
            btnQuanLi.setEnabled(true);
            btnNhapDiem.setEnabled(false);
            btnXemDiem.setEnabled(false);
        }
    }

    public void showAnh() {
        try {
            BufferedImage image = ImageIO.read(new File("src/Main/HinhAnh/Icon/timthumb.jpg"));
            ImageIcon icon = new ImageIcon(image.getScaledInstance(140, 140, image.SCALE_SMOOTH));
            lblAnhTrangChu.setIcon(icon);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnhTrangChu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNhapDiem = new javax.swing.JButton();
        btnXemDiem = new javax.swing.JButton();
        btnQuanLi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(lblAnhTrangChu);
        lblAnhTrangChu.setBounds(20, 20, 140, 140);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("TRANG CHỦ VIETSCHOOL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 60, 400, 50);

        btnNhapDiem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNhapDiem.setText("NHẬP ĐIỂM");
        btnNhapDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapDiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnNhapDiem);
        btnNhapDiem.setBounds(80, 230, 120, 40);

        btnXemDiem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXemDiem.setText("XEM ĐIỂM");
        btnXemDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemDiemActionPerformed(evt);
            }
        });
        getContentPane().add(btnXemDiem);
        btnXemDiem.setBounds(250, 230, 120, 40);

        btnQuanLi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnQuanLi.setText("QUẢN LÍ THÔNG TIN");
        btnQuanLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLiActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuanLi);
        btnQuanLi.setBounds(420, 230, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/HinhAnh/AnhNen/phong-nen-5.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 660, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhapDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapDiemActionPerformed
        Teacher teacher = new Teacher(userName);
        if (GVCN == 1) {
            teacher.GVCN(lop);
        }
    }//GEN-LAST:event_btnNhapDiemActionPerformed

    private void btnXemDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemDiemActionPerformed
        Student student = new Student(userName);
        student.setVisible(true);
    }//GEN-LAST:event_btnXemDiemActionPerformed

    private void btnQuanLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLiActionPerformed
        Administrator ad = new Administrator(userName);
        ad.setVisible(true);
    }//GEN-LAST:event_btnQuanLiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu("TC", "Thanh", 1, "6A").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhapDiem;
    private javax.swing.JButton btnQuanLi;
    private javax.swing.JButton btnXemDiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAnhTrangChu;
    // End of variables declaration//GEN-END:variables
}
